dataset:
  name: StoryReasoning
  split_train: train
  split_test: test
  max_len: 120
  image_size : [60,125]
  K_frames: 4 

training:
  batch_size: 4 
  lr: 0.001
  epochs: 10
  num_workers: 0

model:
  latent_dim: 16
  gru_hidden_dim: 16

loss:
  contrastive_tau: 0.07
  lambda_reid: 0.10
  lambda_ground_mse: 0.10
  lambda_contrast: 0.10
  lambda_entity_pool: 0.05

flags:
# Baseline Architecture
  use_frame_aware_grounding: True  # Activates frame-by-frame logic
  use_contrastive_roi: True        # Helps map keywords to pixels 
  use_entity_pooling: false        # For Experiment 2
  use_cot_text: True               # Uses the GDI tags for reasoning 

# Future Experiments
  use_cross_attention: True        # matches to new changes in model.py
  use_bidirectional: false         # For Experiement 2

